buttons:
  facebook_like:
    name: 'Facebook like'
    enabled: 0
  facebook_share:
    name: 'Facebook share'
    title: 'Share on Facebook'
    enabled: 1
    image: facebook-share.svg
  twitter:
    name: Twitter
    title: 'Share on Twitter'
    enabled: 1
    image: twitter.svg
  googleplus:
    name: Google+
    title: 'Share on Google+'
    enabled: 0
    image: googleplus.svg
  linkedin:
    name: LinkedIn
    title: 'Share on LinkedIn'
    enabled: 0
    image: linkedin.svg
  messenger:
    name: Messenger
    title: 'Share via Messenger'
    enabled: 0
    image: messenger.svg
  viber:
    name: Viber
    title: 'Share via Viber'
    enabled: 0
    image: viber.svg
  whatsapp:
    name: WhatsApp
    title: 'Share via WhatsApp'
    enabled: 0
    image: whatsapp.svg
share_icon:
  image: share-icon.svg
  alt: 'Share icon'
title: 'Share Everywhere'
display_title: 0
style: share_everywhere
include_css: include_css
include_js: include_js
collapsible: '1'
location: links
alignment: right
content_types:
  news: news
  acc_subj: 0
  event: 0
  faq: 0
  page: 0
  pagopa: 0
  person: 0
  press: 0
  software: 0
view_modes:
  article:
    full: full
  page:
    full: full
    embedded: 0
    home_page: 0
    page: 0
    related_content: 0
    rss: 0
    search_index: 0
    search_result: 0
    teaser: 0
    token: 0
  acc_subj:
    full: full
    embedded: 0
    home_page: 0
    page: 0
    related_content: 0
    rss: 0
    search_index: 0
    search_result: 0
    teaser: 0
    token: 0
  event:
    full: full
    embedded: 0
    home_page: 0
    page: 0
    related_content: 0
    rss: 0
    search_index: 0
    search_result: 0
    teaser: 0
    token: 0
  faq:
    full: full
    embedded: 0
    home_page: 0
    page: 0
    related_content: 0
    rss: 0
    search_index: 0
    search_result: 0
    teaser: 0
    token: 0
  news:
    full: full
    embedded: 0
    home_page: 0
    page: 0
    related_content: 0
    rss: 0
    search_index: 0
    search_result: 0
    teaser: 0
    token: 0
  pagopa:
    full: full
    embedded: 0
    home_page: 0
    page: 0
    related_content: 0
    rss: 0
    search_index: 0
    search_result: 0
    teaser: 0
    token: 0
  person:
    full: full
    embedded: 0
    home_page: 0
    page: 0
    related_content: 0
    rss: 0
    search_index: 0
    search_result: 0
    teaser: 0
    token: 0
  press:
    full: full
    embedded: 0
    home_page: 0
    page: 0
    related_content: 0
    rss: 0
    search_index: 0
    search_result: 0
    teaser: 0
    token: 0
  software:
    full: full
    embedded: 0
    home_page: 0
    page: 0
    related_content: 0
    rss: 0
    search_index: 0
    search_result: 0
    teaser: 0
    token: 0
product_types:
  default: default
product_view_modes:
  default:
    full: full
restricted_pages:
  pages: ''
  type: show
weight: 10
_core:
  default_config_hash: GQDoLEOR4E5eoYvZ5ZgimP0c4Edxmwpc_hd9kBF8La0
langcode: it
