default_challenge: recaptcha/reCAPTCHA
description: 'Questa domanda serve per verificare se si tratta di un visitatore umano e per prevenire l''invio automatico di spam.'
administration_mode: false
allow_on_admin_pages: false
add_captcha_description: true
default_validation: 1
persistence: 1
enable_stats: false
log_wrong_responses: false
_core:
  default_config_hash: pfrv6lPS72f5WG1UB4wHkgQV2invlHwVpaCy_mY-ClQ
langcode: it
