types:
  page: page
  acc_subj: 0
  event: 0
  faq: 0
  news: 0
  pagopa: 0
  person: 0
  press: 0
  software: 0
reviser_emails: "example@one.it\r\nexample@two.it"
reviser_title: 'Content changed ([node:nid])'
reviser_message:
  value: "<p>Da configurare</p>\r\n"
  format: full_html
author_title: 'Content changed ([node:nid])'
author_message:
  value: "<p>Da configurare</p>\r\n"
  format: full_html
