module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  agid_base: 0
  agid_blocks: 0
  agid_file_repository: 0
  agid_fixtures: 0
  agid_footer: 0
  agid_migrate_tools: 0
  agid_pagopa: 0
  agid_press: 0
  agid_repo_widget: 0
  agid_software: 0
  automated_cron: 0
  backup_migrate: 0
  ban: 0
  block: 0
  block_class: 0
  block_content: 0
  block_titlelink: 0
  breakpoint: 0
  broken_link: 0
  captcha: 0
  chosen: 0
  chosen_lib: 0
  ckeditor: 0
  config: 0
  config_devel: 0
  config_translation: 0
  content_moderation: 0
  content_translation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  entity_browser: 0
  entity_reference_revisions: 0
  entityqueue: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_entity: 0
  filemime: 0
  filter: 0
  geocoder: 0
  geocoder_field: 0
  geocoder_geofield: 0
  geofield: 0
  image: 0
  imce: 0
  kint: 0
  language: 0
  link: 0
  linkit: 0
  locale: 0
  login_security: 0
  maxlength: 0
  menu_block: 0
  menu_ui: 0
  metatag: 0
  migrate: 0
  migrate_devel: 0
  migrate_drupal: 0
  migrate_google_sheets: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  redirect: 0
  rabbit_hole: 0
  redirect: 0
  recaptcha: 0
  redis: 0
  rename_admin_paths: 0
  rh_node: 0
  rh_taxonomy: 0
  rules: 0
  search: 0
  seckit: 0
  sitemap: 0
  smtp: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  twig_field_value: 0
  typed_data: 0
  update: 0
  user: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  workflows: 0
  xmlsitemap_custom: 0
  xmlsitemap_engines: 0
  extlink: 1
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  views: 10
  paragraphs: 11
  empty_page: 1000
  sparkminimal: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
  agid_back: 0
  italiagov: 0
  agid: 0
profile: sparkminimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: it
